---                                                                                                                       
apiVersion: awx.ansible.com/v1beta1                                                                                       
kind: AWX                                                                                                                 
metadata:                                                                                                                 
  name: awx-deploy                                                                                                         
spec:                                                                                                                     
  service_type: clusterip                                                                                                 
  ingress_type: ingress                                                                                                   
  hostname: my-awx.example.com
  rules:
  - host: my-awx.example.com
    http:
      paths:
      - backend:
          service:
            name: awx-deploy-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
