version: '2'
services:
  jenkins:
      build: /config/tools/jenkins
      image: jenkins/jenkins:args
      privileged: true
      user: root
      ports:
        - "50000:50000"
        - "8080:8080"
      volumes:
        - /config/tools/jenkins/jenkins_home/:/var/jenkins_home
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        default:
          aliases:
            - jenkins
    nginx:
      image: nginx:alpine
      privileged: true
      user: root
      depends_on:
        - jenkins
      volumes:
        - /config/tools/nginx:/etc/nginx/conf.d
      ports:
        - "80:80"
      networks:
        default:
          aliases:
            - nginx
    nexus:
      image: "sonatype/nexus3"
      privileged: true
      user: root
      ports:
        - "8081:8081"
      volumes:
        - /config/tools/nexus:/nexus-data
      networks:
        default:
          aliases:
            - nexus
  networks:
    default:
      driver: bridge
      ipam:
        driver: default
