version: '3'
services: 
  jenkins:
    build: ./jenkins
    image: jenkins/jenkins:args
    privileged: true
    user: root
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes: 
      - /config/jenkins_home/:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      main: 
        aliases: 
          - jenkins
  nginx: 
    image: nginx:alpine
    privileged: true
    user: root
    depends_on: 
      - jenkins
    volumes:
      - /config/nginx:/etc/nginx/conf.d
    ports: 
      - "80:80"
    networks:
      main:
        aliases:
          - nginx
  nexus:
    image: "sonatype/nexus3"
    privileged: true
    user: root
    ports:
      - "8081:8081"
    volumes:
      - /config/nexus:/nexus-data
    networks:
      main:
        aliases:
          - nexus
networks:
  main:
    driver: bridge
