name: Image SBOM Generation

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        default: whoops
      image_tag:
        type: string
        required: true
        default: whoops
      ecr_repo_name:
        type: string
        required: false
        default: ""

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download SBOM Plugin
      run: >-
        curl -sSfl https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh 
        -o install-docker-sbom.sh 
        && chmod +x install-docker-sbom.sh

    - name: Run SBOM Plugin Installer
      run: >- 
        ./install-docker-sbom.sh 
        && docker sbom --version

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Pull Image
      run: >- 
        docker pull 
        ${{ inputs.ecr_repo_name }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
    
    - name: Generate SBOM (JSON)
      run: >-
        docker sbom 
        --format spdx-json 
        --output "${{ inputs.image_name }}-${{ inputs.image_tag }}.json" 
        ${{ inputs.ecr_repo_name }}/${{ inputs.image_name }}:${{ inputs.image_tag }} 

    - name: Copy SBOM to Bucket
      run: >- 
        aws s3 cp 
        "${{ inputs.image_name }}-${{ inputs.image_tag }}.json" 
        s3://barretotechbucket/sbom/ 

    # - uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'us-east-2' 
    #     SOURCE_DIR: 'sbom'
    #     DEST_DIR: 'sbom'
