name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file jenkins/Dockerfile --tag my-image-name:$(date +%s)

    - name: Generate SBOM
      run: docker sbom --output sbom.txt my-image-name:$(date +%s)

    - uses: actions/upload-artifact@v4
      with:
        name: sbom.txt
        path: sbom.txt
