name: Image SBOM Generation

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        default: whoops
      image_tag:
        type: string
        required: true
        default: whoops
      extra_vars:
        type: string
        required: false
        default: ""

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download SBOM PLugin
      run: curl -sSfl https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh -o install-docker-sbom.sh && chmod +x install-docker-sbom.sh

    - name: Run SBOM Installer
      run: ./install-docker-sbom.sh && docker sbom --version && mkdir sbom

    - name: Pull Image
      run: docker pull ${{ inputs.image_name }}:${{ inputs.image_tag }}
    
    # - name: Build the Docker image
    #   run: docker build . --file jenkins/Dockerfile --tag jenkins-sbom:1.0

    - name: Generate SBOM
      run: docker sbom --format spdx-json --output "sbom/${{ inputs.image_name }}-${{ inputs.image_tag }}.json" ${{ inputs.image_name }}:${{ inputs.image_tag }}| jq -c "." > "sbom/${{ inputs.image_name }}-${{ inputs.image_tag }}.json" 

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: sbom.txt
    #     path: sbom.txt

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2' 
        SOURCE_DIR: 'sbom'
        DEST_DIR: 'sbom'
