name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download SBOM PLugin
      run: curl -sSfl https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh -o install-docker-sbom.sh && chmod +x install-docker-sbom.sh

    - name: Run SBOM Installer
      run: ./install-docker-sbom.sh && docker sbom --version
    
    - name: Build the Docker image
      run: docker build . --file jenkins/Dockerfile --tag my-image-name:$(date +%s)

    - name: Generate SBOM
      run: docker sbom --output sbom.txt my-image-name:$(date +%s)

    - uses: actions/upload-artifact@v4
      with:
        name: sbom.txt
        path: sbom.txt
