name: Diagram as Code
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Install Graphviz
       run: >- 
         sudo apt install graphviz

     - name: Diagram-As-Code Install
       run: >-
         pip3 install diagrams-as-code

     - name: Create test.yaml
       run: >-
         cat <<EOF > test.yaml
          diagram:
            name: Web Services Architecture on AWS
            open: true
            resources:
              - id: ecr
                name: ECR
                type: aws.compute.EC2ContainerRegistry
                relates:
                  - to: configdc
                    direction: outgoing
                  - to: vacerts
                    direction: outgoing
              - id: configdc
                name: Config Data Container
                type: aws.general.General
                relates:
                  - to: revproxy-image.revproxy-image-components
                    direction: outgoing
              - id: vacerts
                name: VA Certs Data Container
                type: aws.general.General
                relates:
                  - to: revproxy-image.revproxy-image-components
                    direction: outgoing
              - id: revproxy-image
                name: RevProxy Image
                type: cluster
                of:
                  - id: revproxy-image-components
                    name: RevProxy Img Components
                    type: group
                    of:
                      - id: config-mount
                        name: Config Mount
                        type: aws.compute.ECS
                      - id: vacert-mount
                        name: VA Cert Mount
                        type: aws.compute.ECS
                   
         EOF

     - name: Run DaC code
       run: >-
         diagrams-as-code test.yaml && ls -al

     - name: Deploy
       uses: LarchLiu/actions-save-files@v1
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: publish
         publish_dir: .
         
     - name: Archive code coverage results
       uses: actions/upload-artifact@v4
       with:
         name: code-coverage-report
         path: diagrams_image.png
