name: SBOM (Manual)
on:
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        required: true
        default: whoops
      image_tag:
        type: string
        required: true
        default: whoops
      ecr_repo_name:
        type: string
        required: true
        default: whoops
jobs:
  sbom-generation:
    uses: ./.github/workflows/docker-image.yml
    with:
      image_name: ${{ inputs.image_name }}
      image_tag: ${{ inputs.image_tag }}
      ecr_repo_name:  ${{ inputs.ecr_repo_name }}
    secrets: inherit
